name: .Net WebApp Build

on:
  push:
    branches:
      - github-actions-dotnet-webapp
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Verificar se está na branch github-actions-dotnet-webapp
        run: |
          echo "Branch atual: ${GITHUB_REF#refs/heads/}"
          if [ "${GITHUB_REF#refs/heads/}" != "github-actions-dotnet-webapp" ]; then
            echo "❌ Esta execução não está na branch github-actions-dotnet-webapp. Encerrando."
            exit 1
          fi

      - name: Restaurar e Compilar aplicação .Net
        run: |
          echo "📦 Restaurando dependências..."
          dotnet restore **/*.csproj

          echo "🛠️ Compilando a aplicação..."
          dotnet build **/*.csproj --no-restore

          echo "✅ Build concluído com sucesso!"